### ISSUE TITLE
thoth package found from invectio when using thoth-common or other thoth libraries is not correct

### ISSUE THREAD

**Issue by pacospace** [thoth-station/invectio#99]
**Describe the bug**
thoth package found from invectio when using thoth-common or other thoth libraries is not correct

**To Reproduce**

1. create test.py
```
import pandas as pd
from thoth.report_processing.components.inspection import AmunInspections
from thoth.common import ThothAdviserIntegrationEnum

inspection = AmunInspections()
print(ThothAdviserIntegrationEnum)
df = pd.DataFrame()
```

2. make sure invectio is installed
3. run following command `invectio whatuses test.py `

**Expected behavior**
invectio identifies correct name 

**Screenshots**
```
[fmurdaca@pc-7 13:40:38 ~/work/aicoe/jupyterlab-requirements](add-smart-changelo)$ invectio whatuses test.py 
{
  "report": {
    "test.py": {
      "pandas": [
        "pandas.DataFrame"
      ],
      "thoth": [
        "thoth.common.ThothAdviserIntegrationEnum",
        "thoth.report_processing.components.inspection.AmunInspections"
      ]
    }
  },
  "version": "0.1.0"
}
```

**Additional context**

**Comment by pacospace** [comment]
it's question or bug, because I'm not sure if this is supposed to work with invectio. @fridex any thoughts?

**Comment by pacospace** [comment]
> it's question or bug, because I'm not sure if this is supposed to work with invectio. @fridex any thoughts?

Or the new future project we planned is going to solve this issue?

**Comment by fridex** [comment]
Not sure if we can handle namespaced libraries just by looking into sources and imports. Maybe this could be handled by the endpoint that would give back information about the package based on dotted import (like `sklearn` vs `scikit-learn`).

**Comment by pacospace** [comment]
> Not sure if we can handle namespaced libraries just by looking into sources and imports. Maybe this could be handled by the endpoint that would give back information about the package based on dotted import (like `sklearn` vs `scikit-learn`).

Perfect, thank you @fridex! a warning to be added to jupyterlab-requirements so user can double check the list of packages identified: https://github.com/thoth-station/jupyterlab-requirements/issues/217

**Comment by goern** [comment]
can we conclude something or derive an action?

**Comment by pacospace** [comment]
> can we conclude something or derive an action?

This will be closed by tlegen project.

**Comment by pacospace** [comment]
Depends-On: https://github.com/thoth-station/core/blob/master/docs/intern-projects/Inferring-package-names-out-of-Python-imports.md

**Comment by tlegen-k** [comment]
Hi @pacospace,
I would like to take this issue but not sure yet how to proceed with it.
Can you give a suggestions?

**Comment by pacospace** [comment]
> Hi @pacospace, I would like to take this issue but not sure yet how to proceed with it. Can you give a suggestions?

The solution should be on thamos side https://github.com/thoth-station/thamos/issues/916, not here.

**Comment by fridex** [comment]
Closing this as the functionality is available in thamos.

/close
